name: Update tor exit_addresses + or_addresses

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get IPv4 exit_addresses + or_addresses, delete ports and sort-unique output
        run:  curl -s 'https://onionoo.torproject.org/details?flag=Exit&fields=exit_addresses,or_addresses' | grep -Po '[[,]"\K[^"]*' | grep -v 'or_addresses\|exit_addresses' | sed "s/:[0-9]*$//g" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort -Vu > exits-ipv4.txt
      - name: Get IPv6 exit_addresses + or_addresses, delete ports and sort-unique output
        run:  curl -s 'https://onionoo.torproject.org/details?flag=Exit&fields=exit_addresses,or_addresses' | grep -Po '[[,]"\K[^"]*' | grep -v 'or_addresses\|exit_addresses' | sed "s/:[0-9]*$//g" | grep -oE "\b([a-f0-9:]+:+)+[a-f0-9]+\b" | sort -Vu > exits-ipv6.txt
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.txt'
          disable_globbing: true
          commit_message: Update exits-ipv{4,6}.txt
